{% set name = "PyUnfold" %}
{% set version = "0.4" %}
{% set sha256 = "010bb25d6b73fe773e49bca98ca12b4304ee72e124f8c98eac3690ddbba2cbcd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=2.7,<3.7
    - pip
  run:
    - python >=2.7,<3.7
    - numpy
    - scipy
    - pandas
    - six


test:
  requires:
    - pytest
  imports:
    - pyunfold
    - pyunfold.callbacks
    - pyunfold.mix
    - pyunfold.priors
    - pyunfold.teststat
    - pyunfold.unfold
    - pyunfold.utils
    - pyunfold.tests.test_utils

about:
  home: https://github.com/jrbourbeau/pyunfold
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'PyUnfold: A Python package for iterative unfolding'

  description: |
    PyUnfold is a Python package for implementing iterative unfolding.
  doc_url: https://jrbourbeau.github.io/pyunfold/
  dev_url: https://github.com/jrbourbeau/pyunfold

extra:
  recipe-maintainers:
    - jrbourbeau
