travis:
  secure:
    BINSTAR_TOKEN: QrZ3J7P4a4HFiLUri2+HrPO0Z1yX6rEI83Vzjvg7G8lOuOjxXNHoSKzpyaGEWnwO4QpnCmH5JhKKH2Qg7db6yIuFx0/XZSbedRS4uhwNQbXoqRW4og+eXoXdXk+ssERaz7gUCBT9TX+Vu27nDe4eKx3AjAj6b9BdE5ZMrdFwg6S0ZWrp4ov9lUR6Vfgs88kIrkDchkrTQ6F6Op8dCdDm1oKESq6/p71dtoOrMzSgTjFNJbduEV0q+NVOeeq/UuEMI5K+FC8e3jBiGN3uvzBCd7BUlAPy/+Tl6D8U7K1CS1LwX4kxzMgW/L6n+JbM/zLck3juvE2K7f1HJUcqcv+xiRNYsBP8IFTFgfg6fxr9vnOp8mt9EfSmGfo+bUEI6aTyteeYP2GoRk4gbQnolCiq7qNjMDDghRImatVVtf+X4iIqAxRGSkSrZNi8o54VDbAxGTphijHGphSF+rrQ6g4E2I+xFWMqNAO7rv2Swlw9toLMiyCrYfMxaixTqHQhZX2rRC5uQcumYfvRYdqFYlfFipn35w8FAoIeDAq2gR9DzBe51c2UV2rHiHfDebJFzi3fSWGAUoV1LgvJuNBM3sOxhnAF51i+oxmS5K9ECbAJ23kEIA8Gm3tX2pH3prcRLmRstyN1hIPB1oaVBrH9eyopUCJOzL9bFtsdJ4uDAPyqsvs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
