travis:
  secure:
    BINSTAR_TOKEN: q25CsmFi9Lz1d7+L5iAEu4k0YpBAoK6+RNSK4L+ZwBGfD/eW93QnKFMgpL99ma1AAR4MUvwoBrg0yOrySUmEWfa8lDzZvu+9mzPi8pL4sfcv/wmjYMZSVuGiJiqcCrw7fAoYMXxCjff1MrZZ3vjtu3Ez9G97un7SOL72bU5Fn/KM278A2zp4ANMj2lUjJBJUpzo30VxXuz7qjpPP6u6Z7Vz+ZIzG5OHSTf1t9lcW8scIJ4MR/OdRgxHpecM6Km5mE+Z6n/xL+EPMRu/TDDlGwn3XoGiFRBXwHolHd0HQSiGPOjhYCGXqlws6CtuOLKs2zv+JC3rpJaJ0v7LKegExUtsENmaOU8aAHesbRQe8H9e2MTwYk05pigE7V9sUetZn9SZ8GnKJpgDplhHYwwmP9AS9s/GZrNXBB3jNxEfS/3qNOMlNWfmor4dDIHt0E1gneOQAWdcnUEJTVKyZHrq8pq1+UQDkJXaFUshUmrTPWhLnRpw27g54mIJYFq+lBveu3zQuLvhoZwuz3CVKiH5/+jHwmEuI326sGWg18RYu/wlnUgFFmpH0AEWCXuY2QcWK1ocYZHoA/VtJsIOQyoaN4oRURwO4LcJ0EoX5wpZHuPdHG7NfHjLFgO31Hp6Nl2ruFdf2SNggdI8hzK/WOsYKJtQGuRGdlCwdvfyYumqR1mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
